from typing import TypedDict, List, Dict, Any, Annotated
import operator

"""
### Concept: LangGraph State
In LangGraph, the **State** is the single source of truth for the entire workflow. 
Think of it as a "shared memory" or a "context" that every node (agent) in the graph can read from and write to.

#### Why use a State?
1. **Coordination**: Different agents need to know what others have done (e.g., the CodeGen agent needs the Methodology generated by the Methodology agent).
2. **Persistence**: The state can be saved (checkpointed), allowing you to pause and resume the workflow.
3. **Traceability**: You can look at how the state changed at every step of the process.

#### Key Components:
- **TypedDict**: We use Python's `TypedDict` to define the structure of the state, ensuring type safety.
- **Annotated & operator.add**: This is a powerful LangGraph feature. 
  By default, when a node returns a value for a key that already exists, it *overwrites* it. 
  Using `Annotated[List, operator.add]` tells LangGraph to *append* new values to the existing list instead of replacing it. 
  This is perfect for tracking message history or a list of evaluations.
"""

class GraphState(TypedDict):
    """
    Represents the schema of our hypothesis testing graph state.
    Each key here is a piece of information that our agents will use or produce.
    """
    
    # Concept: Message History
    # We use 'operator.add' so that every time a node returns a message, it gets added to the history.
    messages: Annotated[List[Dict[str, str]], operator.add]
    
    # The core inputs and outputs of the HyTE engine
    hypothesis: str              # The user's initial question or statement
    initial_strategy: str        # High-level approach before knowing specific data tables
    initial_strategy_dict: Dict[str, str] # Dictionary format of the initial strategy
    metadata_context: str        # Information about the available data (tables, columns)
    methodology: str             # The detailed, data-aware plan for analysis
    methodology_pseudocode: str  # Rough pseudocode generated during methodology phase
    granularity_analysis: Dict[str, Any]  # Feasibility analysis: granularity, mergeable groups, joining keys
    
    # Per-KPI artifacts (KPI name -> artifact)
    pseudocode: Dict[str, str]   # KPI name -> Technical logic steps for that KPI's master dataset
    python_code: Dict[str, str]  # KPI name -> Python code for that KPI's master dataset
    kpi_execution_results: Dict[str, str]  # KPI name -> Execution output for that KPI
    kpi_datasets: Dict[str, str] # KPI name -> CSV filename (e.g., "master_dataset_churn_rate.csv")
    
    # Legacy fields (kept for backward compatibility during migration)
    execution_results: str       # Combined execution results (deprecated, use kpi_execution_results)
    artifact_path: str           # Local folder path where result files (CSVs, PNGs) are saved
    
    # Workflow control flags
    current_step: str            # Tracks which stage of the process we are in (e.g., 'started', 'executed')
    kpi_list: List[str]          # List of all KPIs to process
    current_kpi: str             # Currently processing KPI name
    current_kpi_index: int       # Index of current KPI being processed
    retry_count: int             # Tracks how many times we've tried to fix code errors
    refinement_count: int        # Tracks user-requested refinements
    
    # Smart merge results
    merge_report: str            # Report documenting which datasets were merged and which kept separate
    merged_datasets: Dict[str, str]  # Group name -> merged CSV filename
    
    # Concept: Accumulating Results
    # Similar to messages, we want to keep all evaluations and feedback records.
    evaluations: Annotated[List[Dict[str, Any]], operator.add]
    user_feedback: Annotated[List[Dict[str, Any]], operator.add]
    
    # Temporary storage for the most recent feedback for immediate processing
    latest_feedback: str         
